[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vn-project"
version = "0.0.1"
description = "Translate your screen in real-time"
license = { file = "LICENSE" }
classifiers = [ "Programming Language :: Python :: 3" ]
requires-python = ">=3.12"
